version: '3.7'

services:
  backend:
    image: andryscript/backend:0.2
    container_name: backend
    restart: always
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      NODE_ENV: production
      MONGO_URI: mongodb://34.16.147.168:27017/evote
      JWT_SECRET: abc123