version: '3.7'

services:
  backend:
    image: back:latest
    container_name: backend
    restart: always
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      NODE_ENV: production
      MONGO_URI: mongodb://your_root_username:your_root_password@34.132.203.15:6077/evote?authSource=admin
      JWT_SECRET: abc123
    volumes:
      - /home/andrykeeper/evote/services/backend/uploads:/usr/src/app/uploads
